version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-release:
    executor:
      name: node/default
    steps:
      - run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - run:
          command: fossa
          working_directory: ~/prettier-config
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn auto info
            - run:
                command: fossa init
                working_directory: ~/prettier-config
            - run:
                command: fossa analyze
                working_directory: ~/prettier-config
            - run: yarn release
workflows:
  build-and-release:
    jobs:
      - build-and-release
