# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
      - uses: fossas/fossa-action@main
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          run-tests: true

      - name: Prepare repository
        run: |
          echo "Fetching git tags for auto"
          git fetch --unshallow --tags

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn

      - name: Auto Info
        run: yarn auto info

      - name: Auto Release
        run: yarn release

    env:
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      TWITTER_CONSUMER_KEY_SECRET: ${{ secrets.TWITTER_CONSUMER_KEY_SECRET }}
      FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
